#!/usr/bin/env python3
from posixpath import dirname
import sys
import os


i = 0
def main ():
    if len(sys.argv) == 2 :
        path = sys.argv[1]
    else:
        path = dirname(__file__)
    os.environ.setdefault('FINCH_HERE',path)

    from manage import main
    argv = [
        sys.argv[0],
        'runserver',
        '0.0.0.0:8000'
    ]
    main(argv)

if __name__ == "__main__" :
    main()
